### PR TITLE
Command bus

### LINKED ISSUE #29: Command bus

### PR DESCRIPTION
**Pull request by gtoselli**
This close #29

### CODE REVIEW

**Comment by gtoselli** [comment]
@lucagiove the differences with the in-memory event bus are

- _send_ method (vs publish)
- _register_ method (vs subscribe)
- only one handler can exist for each command
- for now, I haven't implemented the _sendAndWaitForHandler_ method

**Comment by lucagiove** [comment]
> @lucagiove the differences with the in-memory event bus are
> 
> * _send_ method (vs publish)
> * _register_ method (vs subscribe)
> * **only one** handler can exist for each command
> * for now, I haven't implemented the _sendAndWaitForHandler_ method

ok but because you don't believe it's useful or time?
Because I think it's even more useful than in EventBus probably. If the aim is decouple.

**Review by lucagiove — APPROVED** [review]

**Comment by lucagiove** [comment]
> > @lucagiove the differences with the in-memory event bus are
> > 
> > * _send_ method (vs publish)
> > * _register_ method (vs subscribe)
> > * **only one** handler can exist for each command
> > * for now, I haven't implemented the _sendAndWaitForHandler_ method
> 
> ok but because you don't believe it's useful or time? Because I think it's even more useful than in EventBus probably. If the aim is decouple.

If it's fine I can implement it.

**Comment by lucagiove** [comment]
another difference is that we should not implement an interface to send multiple commands at once

**Comment by gtoselli** [comment]
> Ok but because you don't believe it's useful or time? Because I think it's even more useful than in EventBus probably. If the aim is decouple. If it's fine I can implement it.

All right, let's add it

**Pull request merged**
